//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicView
{
    public partial class Default
    {
        /// <summary>
        /// ddlYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlRegion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRegion;

        /// <summary>
        /// ddlSex control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSex;

        /// <summary>
        /// btnShow control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnShow;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlPlaceholder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPlaceholder;

        /// <summary>
        /// pnlChart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlChart;

        /// <summary>
        /// pnlSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        /// <summary>
        /// gvSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSummary;

        /// <summary>
        /// hfAgeGroups control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfAgeGroups;

        /// <summary>
        /// hfMaleData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfMaleData;

        /// <summary>
        /// hfFemaleData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfFemaleData;

        /// <summary>
        /// hfChartTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfChartTitle;

        /// <summary>
        /// hfSexFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSexFilter;
    }
}
